[package]
name = "actix-web-example"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.12"
static-filez = { version = "0.1", path = "../../" }
